# Blessman Newton

## 01-intro Homework

In [472]:
import numpy as np
import pandas as pd
import requests

## Q1 Pandas version

In [474]:
pd.__version__

'2.2.2'

## Extractin dataset use requests

In [476]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"

response = requests.get(url)

with open("laptops.csv", "wb") as file:
    file.write(response.content)

In [477]:
df = pd.read_csv("laptops.csv")
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

## Q2 Records count

In [479]:
num_records = df.shape[0]
print(f"Number of records: {num_records}")

Number of records: 2160


## Q3 Laptop brands

In [481]:
num_brands = pd.Series(df['Brand']).count()
print(f"Number of brands: {num_brands}")

Number of brands: 2160


## Q4 Missing values

In [483]:
missing_value = df.isnull().sum()
num_columns_with_missing = (missing_value > 0).sum()
print(f"Number of columns with missing values: {num_columns_with_missing}")


Number of columns with missing values: 3


## Q5 Maximum final price

In [485]:
dell_brand = df[df['Brand'] == 'Dell']
max_price = dell_brand['Final Price'].max()

print(f"The maximum final price of Dell notebooks is: {max_price}")


The maximum final price of Dell notebooks is: 3936.0


## Q6 Median value of Screen

In [487]:
screen_value = df['Screen']
median_screen = screen_value.median()
print(f"The mean value in the Screen column is: {median_screen}")


The mean value in the Screen column is: 15.6


##### Median value of Screen

In [489]:
most_frequent_screen = screen_value.mode()[0]
print(f"The most frequent value in the Screen column is: {most_frequent_screen}")


The most frequent value in the Screen column is: 15.6


#####  fill the missing values in Screen column with the most frequent value

In [491]:
filling_missing_value_in_screen = screen_value.fillna(most_frequent_screen, inplace=True)

In [492]:
missing_values_after_fill = screen_value.isnull().sum()
print(f"Number of missing values in the Screen column after filling: {missing_values_after_fill}")


Number of missing values in the Screen column after filling: 0


##### Median value of Screen

In [494]:
screen_value.median()

15.6

In [495]:
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

## Q7. Sum of weights

In [497]:
innjoo_laptops = df[df['Brand'] == 'Innjoo']
innjoo_laptops

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

##### display of RAM, Storage and Screen Columns

In [499]:
R_S_S_only = innjoo_laptops[['RAM', 'Storage', 'Screen']]

In [500]:
# converting to numpy array
X = R_S_S_only.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

##### matrix-matrix multiplication

In [502]:
XTX = X.T @ X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

##### inverse of XTX

In [504]:
XTX_inv = np.linalg.inv(XTX)
print(f"Inverse of XTX: {XTX_inv}")

Inverse of XTX: [[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


##### Creating an array

In [506]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [507]:
XTX_inv_XT = (XTX_inv @ X.T)
XTX_inv_XT

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [508]:
XTX_inv_XT.shape

(3, 6)

In [509]:
y.shape

(6,)

##### Multiply the inverse of XTX with the transpose of X, and then multiply the result by y

In [511]:
w = XTX_inv_XT @ y
w

array([45.58076606,  0.42783519, 45.29127938])

##### sum of all the elements of the result

In [513]:
sum_w = w.sum()

print("Sum of all elements in w:", sum_w)

Sum of all elements in w: 91.2998806299555
