# Machine Learning Zoomcamp

#### 1.7 Introduction to Numpy

#### Plan:

<ul> <li>Creating arrays</li>
    <li>Multi-dementional arrays</li>
    <li>Ramdomly generated arrays</li>
    <li>Element-wise operation
        <ul>
            <li>Comparision operation</li>
            <li>Logical Operation</li>
        </ul>
    </li>
    <li>Summarizing operation</li>
</ul>


In [8]:
import numpy as np

In [9]:
np

<module 'numpy' from 'C:\\Users\\bless\\AppData\\Roaming\\Python\\Python312\\site-packages\\numpy\\__init__.py'>

In [10]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.full(10, 4)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [13]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
lin = np.linspace(0, 100, 11)
lin

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [15]:
lin[3] = 12
lin

array([  0.,  10.,  20.,  12.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dementional arrays

In [17]:
np.zeros((5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
n = np.array([
    [2, 4, 1],
    [6, 3, 6],
    [2, 8, 9],
    [6, 1, 2],
])

n

array([[2, 4, 1],
       [6, 3, 6],
       [2, 8, 9],
       [6, 1, 2]])

In [19]:
n[3, 2] = 1
n

array([[2, 4, 1],
       [6, 3, 6],
       [2, 8, 9],
       [6, 1, 1]])

In [20]:
n[2] = [2, 3, 3]
n

array([[2, 4, 1],
       [6, 3, 6],
       [2, 3, 3],
       [6, 1, 1]])

In [21]:
n[:, 1]

array([4, 3, 3, 1])

In [22]:
n[:, 1] = [1,0,0,1]
n

array([[2, 1, 1],
       [6, 0, 6],
       [2, 0, 3],
       [6, 1, 1]])

### Ramdomly generated arrays

In [67]:
np.random.rand(5,2)

array([[0.08074127, 0.7384403 ],
       [0.44130922, 0.15830987],
       [0.87993703, 0.27408646],
       [0.41423502, 0.29607993],
       [0.62878791, 0.57983781]])

In [69]:
np.random.seed(5)
np.random.rand(5,2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

## Element-wise operation

In [72]:
a = np.array([1, 4, 6, 7])

In [74]:
a + 100

array([101, 104, 106, 107])

In [76]:
a // 10

array([0, 0, 0, 0], dtype=int32)

In [80]:
b = 2 * ( a // 2 + 7) /  5
b

array([2.8, 3.6, 4. , 4. ])

In [82]:
a + b

array([ 3.8,  7.6, 10. , 11. ])

### Comparision operation &  Logical Operation 

In [88]:
a >= 2

array([False,  True,  True,  True])

In [90]:
a == 3

array([False, False, False, False])

In [92]:
a = b

In [96]:
a <= b

array([ True,  True,  True,  True])

## Summarizing operation

In [103]:
a = np.array([
    2, 4, 7, 0.9, 39, 12
])

In [105]:
a.max()

39.0

In [107]:
a.min()

0.9

In [109]:
a.std()

13.120012279804552

In [111]:
a.sum()

64.9

In [113]:
a.mean()

10.816666666666668